name: new_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  flutter_local_notifications: ^9.0.0
  timezone: ^0.8.0
  android_intent_plus: ^2.0.0
  url_launcher: ^6.0.20
  googleapis_auth: ^1.0.0
  permission_handler: ^10.0.0
  flutter_slidable: ^3.1.0
  reorderables: ^0.4.2
  fl_chart: ^0.36.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png