name: new_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  flutter_local_notifications: ^9.0.0
  timezone: ^0.8.0
  reorderables: ^0.4.2
  url_launcher: ^6.0.20
  googleapis_auth: ^1.0.0
  permission_handler: ^10.0.0
  flutter_slidable: ^3.1.0
  fl_chart: ^0.68.0
  intro_slider: ^4.2.1
  shared_preferences: ^2.0.10
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/notepad_background.png  # Ensure the notepad background image is in the correct path

  fonts:
    - family: Shadows Into Light
      fonts:
        - asset: assets/fonts/ShadowsIntoLight-Regular.ttf  # Ensure the font file is in the correct path
